[package]
name = "web_api_client"
version = "0.1.17"
authors = ["kykc"]
build = "build.rs"
license = "MIT"
description = "Simple HTTP client with GTK UI written in Rust"

[dependencies]
gio = "^0.5"
gdk = "^0.9"
serde = "^1.0"
serde_derive = "^1.0"
reqwest = "^0.9"
dirs = "^1.0"
glib = "^0.6"
mime = "^0.3"
rusqlite = "^0.14"
quick-xml = "^0.12"
html5ever = "^0.22"

[dev-dependencies]
cargo-deb = "^1.12"

[dependencies.sourceview]
features = ["v3_20"]
version = "^0.5"

[dependencies.gtk]
version = "^0.5"
features = ["v3_20"]

[dependencies.serde_json]
version = "^1.0"
features = ["preserve_order"]

[target.'cfg(windows)'.build-dependencies]
windres = "^0.2"

[package.metadata.deb]
depends = "libxrender1 (>= 1:0.9.10), libxcursor1 (>= 1:1.1.15), libgcrypt20 (>= 1.8.1), libfreetype6 (>= 2.8.1), libssl1.1 (>= 1.1.0g), libgdk-pixbuf2.0-0 (>= 2.36.11), libbsd0 (>= 0.8.7), libxrandr2 (>= 2:1.5.1), libwayland-client0 (>= 1.14.0), libicu60 (>= 60.2), libxau6 (>= 1:1.0.8), libgraphite2-3 (>= 1.3.11), libthai0 (>= 0.1.27), libsystemd0 (>= 237), libuuid1 (>= 2.31.1), libpcre3 (>= 2:8.39), libpixman-1-0 (>= 0.34.0), libxdamage1 (>= 1:1.1.4), libwayland-cursor0 (>= 1.14.0), libglib2.0-0 (>= 2.56.2), libpangocairo-1.0-0 (>= 1.40.14), libxcomposite1 (>= 1:0.4.4), libxcb-shm0 (>= 1.13), libxfixes3 (>= 1:5.0.3), libx11-6 (>= 2:1.6.4), libwayland-egl1-mesa (>= 18.0.5), libgtksourceview-3.0-1 (>= 3.24.7), libblkid1 (>= 2.31.1), libsqlite3-0 (>= 3.22.0), libcairo-gobject2 (>= 1.15.10), libxkbcommon0 (>= 0.8.0), liblz4-1 (>= 0.0~r131), libselinux1 (>= 2.7), libgpg-error0 (>= 1.27), libxext6 (>= 2:1.3.3), libatspi2.0-0 (>= 2.28.0), libexpat1 (>= 2.2.5), zlib1g (>= 1:1.2.11.dfsg), libepoxy0 (>= 1.4.3), libfontconfig1 (>= 2.12.6), libcairo2 (>= 1.15.10), libdbus-1-3 (>= 1.12.2), libc6 (>= 2.27), libxinerama1 (>= 2:1.1.3), libxdmcp6 (>= 1:1.1.2), libpangoft2-1.0-0 (>= 1.40.14), liblzma5 (>= 5.2.2), libxi6 (>= 2:1.7.9), libgcc1 (>= 1:8), libgtk-3-0 (>= 3.22.30), libharfbuzz0b (>= 1.7.2), libstdc++6 (>= 8), libpng16-16 (>= 1.6.34), libxcb1 (>= 1.13), libpango-1.0-0 (>= 1.40.14), libatk-bridge2.0-0 (>= 2.26.2), libxml2 (>= 2.9.4+dfsg1), libmount1 (>= 2.31.1), libxcb-render0 (>= 1.13), libffi6 (>= 3.2.1), libatk1.0-0 (>= 2.28.1), libdatrie1 (>= 0.2.10)"
assets = [
    ["target/release/web_api_client", "usr/bin/auweb", "755"],
    ["assets/auweb.desktop", "usr/share/applications/", "644"],
    ["assets/auweb.png", "usr/share/icons/", "644"],
    ["assets/auweb48.png", "usr/share/icons/hicolor/48x48/apps/auweb.png", "644"],
    ["assets/tomorrownighteighties.xml", "usr/share/gtksourceview-3.0/styles/", "644"],
]
